import axios from 'axios'

const WIX_SITE_ID = '3276cc94-067b-4dd0-b91b-9c40b75ee130'
const WIX_METASITE_ID = '369e8246-4291-4cda-8fac-7329bb789fdc'
const WIX_ACCOUNT_ID = '1fdf8f7f-845e-4dec-be53-ba981fc9c691'
const WIX_API_KEY = 'IST.eyJraWQiOiJQb3pIX2FDMiIsImFsZyI6IlJTMjU2In0.eyJkYXRhIjoie1wiaWRcIjpcIjdjNmJiOTRjLTRiODItNGY0OC05ZmRiLTViMWQzMDg1NGRlNVwiLFwiaWRlbnRpdHlcIjp7XCJ0eXBlXCI6XCJhcHBsaWNhdGlvblwiLFwiaWRcIjpcImU2NDA2NmRhLWE4NmUtNDhmYS05MDVhLWVlM2JmOTEyYjk4N1wifSxcInRlbmFudFwiOntcInR5cGVcIjpcImFjY291bnRcIixcImlkXCI6XCIxZmRmOGY3Zi04NDVlLTRkZWMtYmU1My1iYTk4MWZjOWM2OTFcIn19IiwiaWF0IjoxNzUzMzU4ODQ4fQ.V9kFxJB_-0J1pPuRq2FFJWNiKrJOQFAxA06x3kRXSRRaGkpO2wve1wSFZKQBhAaO-AhGIeQ2uNJwtbRatqfNLlGDg46VvsJByK6G823vZKoZ-nnALhTfxZ8MbcQHwcRfQ3IBExUo7P84O4OO1HG80Wk8TFHmZpy7_j44yaCPstFlfimVAyrlM_2aamsfYO9Uf88zf1c7hlabfPFsTstqUczNYjNydngJGzjhaNv21ioHSAIfR13UwPgcMHBPwpD_ZymLGLsW6jVmKQ1LGK6eUyqsUHqvq_1QV450aN1fgI5MrwiOsDNkr3czETt-Ock1Q7s7OClh_rypLWBIPnO-tQ'

export interface WixBlogPost {
  title: string
  content: string
  slug?: string
  status?: 'PUBLISHED' | 'DRAFT'
}

export interface WixCollection {
  id: string
  displayName: string
  fields: Record<string, any>
}

export class WixService {
  private get headers() {
    return {
      'Authorization': WIX_API_KEY,
      'wix-account-id': WIX_ACCOUNT_ID,
      'Content-Type': 'application/json'
    }
  }

  async ping(): Promise<boolean> {
    try {
      console.log('🔄 Testing Wix API connection...')
      
      // Test the connection by trying to list collections
      const response = await axios.get('https://www.wixapis.com/wix-data/v2/collections', {
        headers: this.headers
      })
      
      console.log('✅ Wix API connection successful!')
      console.log(`📊 Found ${response.data.collections?.length || 0} collections`)
      return true
    } catch (error: any) {
      console.error('🚨 Wix API connection error:', error.response?.data || error.message)
      return false
    }
  }

  async listCollections(): Promise<WixCollection[]> {
    try {
      const response = await axios.get('https://www.wixapis.com/wix-data/v2/collections', {
        headers: this.headers
      })
      return response.data.collections || []
    } catch (error) {
      console.error('Error listing Wix collections:', error)
      throw new Error('Failed to fetch Wix collections')
    }
  }

  async getCollectionItems(collectionId: string): Promise<any[]> {
    try {
      const response = await axios.get(
        `https://www.wixapis.com/wix-data/v2/collections/${collectionId}/items`,
        { headers: this.headers }
      )
      return response.data.items || []
    } catch (error) {
      console.error('Error getting collection items:', error)
      throw new Error('Failed to fetch collection items')
    }
  }

  async createBlogPost(post: WixBlogPost): Promise<any> {
    try {
      const response = await axios.post(
        'https://www.wixapis.com/blog/v3/posts',
        {
          post: {
            title: post.title,
            contentText: post.content,
            slug: post.slug || post.title.toLowerCase().replace(/\s+/g, '-'),
            status: post.status || 'DRAFT'
          }
        },
        { headers: this.headers }
      )
      return response.data
    } catch (error) {
      console.error('Error creating blog post:', error)
      throw new Error('Failed to create blog post')
    }
  }

  async publishToWixBlog(title: string, content: string, platform: string): Promise<any> {
    const blogContent = `
      <h2>Generated Social Media Content for ${platform}</h2>
      <div class="social-content">
        ${content.split('\n').map(line => `<p>${line}</p>`).join('')}
      </div>
      <p><em>Generated by SocialAI - AI-powered social media content generator</em></p>
    `

    return this.createBlogPost({
      title: `${platform} Content: ${title}`,
      content: blogContent,
      slug: `${platform.toLowerCase()}-${title.toLowerCase().replace(/\s+/g, '-')}`
    })
  }
}

export const wixService = new WixService()